# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Ability": "00_characters.ipynb",
         "Character": "00_characters.ipynb",
         "Mage": "00_characters.ipynb",
         "Demon": "00_characters.ipynb",
         "init_player": "01_game.ipynb",
         "combat": "01_game.ipynb",
         "COMBAT_OPTIONS": "01_game.ipynb",
         "game_loop": "01_game.ipynb",
         "play": "02_cli.ipynb"}

modules = ["characters.py",
           "game.py",
           "cli.py"]

doc_url = "https://ncoop57.github.io/mages/"

git_url = "https://github.com/ncoop57/mages/tree/master/"

def custom_doc_links(name): return None
