# AUTOGENERATED! DO NOT EDIT! File to edit: 02_cli.ipynb (unless otherwise specified).

__all__ = ['play']

# Cell
from fastcore.script import call_parse, Param
from .game import init_player, game_loop

# Cell
@call_parse
def play(n: Param("The number of bosses you want to encounter.", int) = 5):
    player = init_player()
    game_loop(player, n)