name: CI
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install nbdev jupyter twine wheel
        pip install -e .
    - name: Publishing to PyPi
      env:
        TWINE_USERNAME: ${{secrets.PYPI_USERNAME}}
        TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}
        TWINE_REPOSITORY: testpypi
      run: |
        make release
        nbdev_bump_version
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update version number
        branch: main